PY ?= python3

.PHONY: install test lint fixtures media-guard blender-verify pose-verify gate dist

install:
	$(PY) -m pip install -e "core[dev]"

test:
	cd core && $(PY) -m pytest tests

lint:
	$(PY) -m ruff check core/src core/tests addon/riggermortis_addon xtask/export_fixture_rigs.py xtask/build_rigify_rigs.py xtask/import_and_extract.py xtask/render_demos.py xtask/benchmark_poses.py xtask/foot_lock_gate.py

fixtures:
	$(PY) xtask/export_fixture_rigs.py

# Demo media is always generated by the pipeline; it must never be committed.
dist:
	@cp README.md core/README.md
	cd core && $(PY) -m build --sdist --wheel -o ../dist/
	@python3 -m twine check dist/*
	@rm -f core/README.md

media-guard:
	@n=$$(git ls-files media/ | wc -l); \
	if [ "$$n" -ne 0 ]; then \
		echo "media/ contains $$n committed file(s) — demo media is generated headlessly and never hand-committed" >&2; \
		exit 1; \
	fi; \
	for want in docs/media/boom.gif docs/media/ui_screenshot.png; do \
		if ! git ls-files --error-unmatch "$$want" > /dev/null 2>&1; then \
			echo "missing $$want — README hero artifact is a pipeline output (regen: bash xtask/render_boom.sh / xtask/ui_screenshot.sh)" >&2; \
			exit 1; \
		fi; \
	done; \
	extra=$$(git ls-files docs/media/ | grep -Fxv -e docs/media/boom.gif -e docs/media/ui_screenshot.png || true); \
	if [ -n "$$extra" ]; then \
		echo "docs/media/ contains unallowlisted file(s): $$extra — hero media is pinned to the two pipeline outputs" >&2; \
		exit 1; \
	fi; \
	echo "media guard clean: media/ empty; docs/media/ = the 2 pinned pipeline outputs"

# Full Phase 0 gate against a real local Blender (needs `make install` first)
blender-verify:
	bash xtask/blender_verify.sh

# P1-6/P1-7 gate + P2-3 bake gate: payload apply, mirror, clear, review
# overlay, multi-figure switch, 2-frame action bake on real rigs
# (needs downloaded models: rigpose models download all)
pose-verify:
	bash xtask/verify_pose_apply.sh

gate: lint test media-guard blender-verify
	@echo "PHASE 0 GATE: PASS"
