PY ?= python3

.PHONY: install test lint fixtures media-guard blender-verify pose-verify gate

install:
	$(PY) -m pip install -e "core[dev]"

test:
	cd core && $(PY) -m pytest tests

lint:
	$(PY) -m ruff check core/src core/tests addon/riggermortis_addon xtask/export_fixture_rigs.py xtask/build_rigify_rigs.py xtask/import_and_extract.py xtask/render_demos.py xtask/benchmark_poses.py

fixtures:
	$(PY) xtask/export_fixture_rigs.py

# Demo media is always generated by the pipeline; it must never be committed.
media-guard:
	@n=$$(git ls-files media/ | wc -l); \
	if [ "$$n" -ne 0 ]; then \
		echo "media/ contains $$n committed file(s) — demo media is generated headlessly and never hand-committed" >&2; \
		exit 1; \
	fi; \
	echo "media/ clean: no committed files"

# Full Phase 0 gate against a real local Blender (needs `make install` first)
blender-verify:
	bash xtask/blender_verify.sh

# P1-6/P1-7 gate: payload apply + mirror + clear + review overlay on real rigs
# (needs downloaded models: rigpose models download all)
pose-verify:
	bash xtask/verify_pose_apply.sh

gate: lint test media-guard blender-verify
	@echo "PHASE 0 GATE: PASS"
