PY ?= python3

.PHONY: install test lint fixtures media-guard blender-verify pose-verify export-verify gate dist

install:
	$(PY) -m pip install -e "core[dev]"

test:
	cd core && $(PY) -m pytest tests

lint:
	$(PY) -m ruff check core/src core/tests addon/riggermortis_addon mcp/riggermortis_mcp.py mcp/session_bridge.py xtask/export_fixture_rigs.py xtask/build_rigify_rigs.py xtask/import_and_extract.py xtask/render_demos.py xtask/benchmark_poses.py xtask/foot_lock_gate.py xtask/hip_stab_gate.py xtask/walk_media.py xtask/assemble_walk.py xtask/walk_docs.py xtask/session_probe.py xtask/walk_job.py

fixtures:
	$(PY) xtask/export_fixture_rigs.py

# Demo media is always generated by the pipeline; it must never be committed.
dist:
	@cp README.md core/README.md
	cd core && $(PY) -m build --sdist --wheel -o ../dist/
	@python3 -m twine check dist/*
	@rm -f core/README.md

WALK_GIFS = docs/media/walk_lock_metarig.gif docs/media/walk_lock_seedsan.gif \
	docs/media/walk_lock_xbot.gif docs/media/walk_3rigs.gif

media-guard:
	@n=$$(git ls-files media/ | wc -l); \
	if [ "$$n" -ne 0 ]; then \
		echo "media/ contains $$n committed file(s) — demo media is generated headlessly and never hand-committed" >&2; \
		exit 1; \
	fi; \
	for want in docs/media/boom.gif docs/media/ui_screenshot.png $(WALK_GIFS); do \
		if ! git ls-files --error-unmatch "$$want" > /dev/null 2>&1; then \
			echo "missing $$want — hero media is pinned to pipeline outputs (regen: bash xtask/render_boom.sh / xtask/ui_screenshot.sh / make walk-gifs)" >&2; \
			exit 1; \
		fi; \
	done; \
	extra=$$(git ls-files docs/media/ | grep -Fxv -e docs/media/boom.gif -e docs/media/ui_screenshot.png $(patsubst %,-e %,$(WALK_GIFS)) || true); \
	if [ -n "$$extra" ]; then \
		echo "docs/media/ contains unallowlisted file(s): $$extra — hero media is pinned to the pipeline outputs (extending the allowlist is a deliberate, documented change in the same commit as the media)" >&2; \
		exit 1; \
	fi; \
	echo "media guard clean: media/ empty; docs/media/ = the 6 pinned pipeline outputs"

# Full Phase 0 gate against a real local Blender (needs `make install` first)
blender-verify:
	bash xtask/blender_verify.sh

# P1-6/P1-7 gate + P2-3 bake gate: payload apply, mirror, clear, review
# overlay, multi-figure switch, 2-frame action bake on real rigs
# (needs downloaded models: rigpose models download all)
pose-verify:
	bash xtask/verify_pose_apply.sh

# P2-7 export gate: bake → FBX/glTF → re-import round-trip on a real Blender
# (self-contained: no models, no local assets)
export-verify:
	bash xtask/export_clip.sh

# P2-8 walk media: labeled SYNTHETIC walk across 3 real rigs (raw|locked
# bakes, headless renders, side-by-side GIFs into docs/media/, WALKRIGS docs
# block). Needs LOCAL rigs (out/real_rigs/, git-ignored) — not a CI target.
walk-gifs:
	bash xtask/render_walk_gifs.sh

# P3-5/P3-7 session-bridge gate: MCP server loopback <-> REAL Blender add-on
# client, enqueue -> execute -> structured result, incl. the P3-7 bake_action
# (real fixture job, re-eval <= 0.5 deg) and render_turntable — self-contained
# (no models, no local assets). Starts nothing external: 127.0.0.1 only.
session-verify:
	bash xtask/session_verify.sh

# P3-7 agent demo (the launch asset): a scripted agent over the server's
# stdio drives a live Blender inspect -> pose -> animate -> turntable on the
# LOCAL rigs; GIF + transcript into docs/. Needs out/real_rigs/ + models
# (git-ignored) — not a CI target.
agent-demo:
	bash xtask/agent_demo.sh

gate: lint test media-guard blender-verify session-verify
	@echo "PHASE 0 GATE: PASS"
