#!/usr/bin/env bash
# P4-8 manga pipeline ("Paper Dart"): the Blender spawn + every artifact
# MOVE live HERE (D-009 — the .py renders under one OUT_DIR only; the shell
# copies the VISUALLY CHECKED artifacts into docs/manga/).
#
#   sheet : the 20-beat pose contact sheet (the visual-check loop)
#   pages : 6 story pages + hero + parse-back-verified PDF + docs copies
#   all   : sheet then pages
#
# Usage: BLENDER=... bash xtask/manga_build.sh [sheet|pages|all]
set -euo pipefail

BLENDER=${BLENDER:-blender}
REPO=$(cd "$(dirname "$0")/.." && pwd)
MODE=${1:-all}
OUT=${RMANGA_OUT:-"$REPO/out/manga"}

mkdir -p "$OUT"
"$BLENDER" -b --python "$REPO/xtask/manga_build.py" -- "$OUT" "$MODE"

if [ "$MODE" = "sheet" ]; then
  echo "sheet in $OUT/sheet (inspection artifact, git-ignored)"
  exit 0
fi

# The docs copies: only after the .py printed its own PASS lines (page
# renders + PDF parse-back verified inside the run). Every shipped asset
# is GENERATED by this pipeline; the media-guard pins the set in the same
# commit (the media rule).
DOCS="$REPO/docs/manga"
mkdir -p "$DOCS"
i=1
for p in manga_dart_p1 manga_dart_p2 manga_dart_p3 manga_dart_p4 manga_dart_p5 manga_dart_p6; do
  cp "$OUT/pages/$p.png" "$DOCS/page_0$i.png"
  i=$((i + 1))
done
cp "$OUT/pages/manga_dart_hero.png" "$DOCS/hero_3styles.png"
cp "$OUT/paper_dart.pdf" "$DOCS/paper_dart.pdf"
echo "docs/manga/: 6 pages + hero_3styles.png + paper_dart.pdf (GENERATED — every asset from this pipeline)"
