#!/usr/bin/env bash
# P2-8: the labeled SYNTHETIC walk across three real rigs.
#
# Per rig x mode (raw | locked): condition(hip_stabilize) -> detect -> lock ->
# the add-on's real bake_action -> headless bone-proxy renders + manifest.
# Then: side-by-side GIFs into docs/media/ (2-up raw|locked per rig + the
# 3-rig locked hero) and the WALKRIGS docs block in docs/BENCHMARKS.md.
#
# MEDIA RULE: every committed walk GIF is generated by THIS script — never
# hand-made. The clip is the labeled synthetic generator (xtask/hip_stab_gate.py);
# the real walking clip stays NEEDS-HUMAN (out/video_smoke/SOURCES.md).
#
# Needs: BLENDER (default: blender), local rigs under out/real_rigs/
# (git-ignored), pillow. Not a CI target (CI has no local rigs).
set -euo pipefail

BLENDER=${BLENDER:-blender}
REPO=$(cd "$(dirname "$0")/.." && pwd)
OUT="$REPO/out/p28"
RIGS="$REPO/out/real_rigs"
DOCS_MEDIA="$REPO/docs/media"

mkdir -p "$OUT" "$DOCS_MEDIA"

for f in "$RIGS/metarig.blend" "$RIGS/Seed-san.vrm" "$RIGS/Xbot.glb"; do
  if [ ! -s "$f" ]; then
    echo "missing $f — build it first (see docs/BENCHMARKS.md reproduce blocks)" >&2
    exit 1
  fi
done

render_one() {
  local label=$1 rig=$2 mode=$3
  echo "== walk: $label $mode"
  RM_CORE_SRC="$REPO/core/src" RM_ADDON_DIR="$REPO/addon" \
    "$BLENDER" -b -P "$REPO/xtask/walk_media.py" -- \
    --rig "$rig" --label "$label" --mode "$mode" \
    --out "$OUT" --stride 2 --size 640 480 \
    2>&1 | tee "$OUT/${label}_${mode}.log" | grep -E "RM_WALK|error:" || true
  grep -q "RM_WALK ${label} ${mode}: PASS" "$OUT/${label}_${mode}.log"
}

render_one metarig "$RIGS/metarig.blend" raw
render_one metarig "$RIGS/metarig.blend" locked
render_one seedsan "$RIGS/Seed-san.vrm" raw
render_one seedsan "$RIGS/Seed-san.vrm" locked
render_one xbot "$RIGS/Xbot.glb" raw
render_one xbot "$RIGS/Xbot.glb" locked

echo "== assembling GIFs -> docs/media/"
python3 "$REPO/xtask/assemble_walk.py" \
  --cell "raw=$OUT/metarig_raw.manifest.json" \
  --cell "locked=$OUT/metarig_locked.manifest.json" \
  --out "$DOCS_MEDIA/walk_lock_metarig.gif"
python3 "$REPO/xtask/assemble_walk.py" \
  --cell "raw=$OUT/seedsan_raw.manifest.json" \
  --cell "locked=$OUT/seedsan_locked.manifest.json" \
  --out "$DOCS_MEDIA/walk_lock_seedsan.gif"
python3 "$REPO/xtask/assemble_walk.py" \
  --cell "raw=$OUT/xbot_raw.manifest.json" \
  --cell "locked=$OUT/xbot_locked.manifest.json" \
  --out "$DOCS_MEDIA/walk_lock_xbot.gif"
python3 "$REPO/xtask/assemble_walk.py" \
  --cell "metarig=$OUT/metarig_locked.manifest.json" \
  --cell "seedsan=$OUT/seedsan_locked.manifest.json" \
  --cell "xbot=$OUT/xbot_locked.manifest.json" \
  --out "$DOCS_MEDIA/walk_3rigs.gif"

echo "== docs block"
python3 "$REPO/xtask/walk_docs.py" --dir "$OUT"

echo ""
echo "P2-8 WALK MEDIA PIPELINE: PASS (synthetic-labeled; 4 GIFs in docs/media/)"
