"""P8-9 review-UX gate (run INSIDE Blender, headless) — the RM_RUX rows
through the REAL add-on operators and apply paths. couple_gate.py's sibling
for the review-UX rock (the same house shape: real machinery, grep-pinned
lines, exit 0 only if all PASS).

The probe (xtask/review_ux_probe.py) owns the DECLARED time-to-fix
instrument core-side; this gate proves the interactive half: the five
operators (rm.finger_fix / rm.face_trim / rm.figure_flip / rm.pin_retarget /
rm.pin_confirm) drive the core affordances through the REAL apply paths
(pose_apply / scene_apply), refuse loudly, keep the untouched path
byte-identical, and run as byte-identical twins.

ZERO gate-side file IO (the S27 couple-gate lesson): the operators read the
payload files verify_pose_apply.sh already generated (RM_PAYLOADS); every
fixture scene lives in memory (couple_gate's canonical-exact rig builders —
ONE fixture copy).

Rows:
1. RUX-GATE-OPS      — the five operators registered.
2. RUX-GATE-FINGER   — rm.finger_fix authors a chain through the REAL apply
   (the metarig carries no finger bones: the loud capability note is the
   EXPECTED shape — never a silent no-op; the core chain's canonical
   segment lengths + confidence 1.0 + cleared ledger are verified).
3. RUX-GATE-FACE     — rm.face_trim authors a param through the REAL apply.
4. RUX-GATE-FIGURE   — rm.figure_flip re-applies a REAL multi-figure payload
   with the mirrored figure (pins ride); quats match the direct-path apply.
5. RUX-GATE-PIN      — the pin affordances through the LIBRARY path on an
   in-memory couple fixture: retarget + confirm produce authored pins
   (confidence 1.0, provenance note) and the scene re-applies; the OPERATOR
   pin path refuses loudly on a pin-less payload (folded into REFUSE).
6. RUX-GATE-UNTOUCHED — a clean payload re-applies byte-identically with
   all affordances registered (the certified apply moved no byte).
7. RUX-GATE-REFUSE   — bad props (unknown hand/finger/direction/param/
   figure, pin op on a pin-less payload) return CANCELLED loudly.
8. RUX-GATE-DETERM   — the finger fix runs twice; applied quats identical.
9. RUX-GATE-T2F      — the op wall-clock per scripted click-through,
   published alongside the probe's declared interaction model.

Usage: blender -b --python xtask/review_ux_gate.py
Env: RM_CORE_SRC, RM_ADDON_DIR, RM_METARIG_BLEND, RM_PAYLOADS.
Prints RM_RUX lines; exit 0 only if every row PASSes.
"""
from __future__ import annotations

import json
import math
import os
import sys
import time

sys.path.insert(0, os.environ["RM_CORE_SRC"])
sys.path.insert(0, os.environ["RM_ADDON_DIR"])
sys.path.insert(0, os.environ["RM_XTASK"])

import bpy  # noqa: E402
import couple_gate  # noqa: E402  (sibling gate: the canonical-exact rig builders)
import riggermortis as core  # noqa: E402
from mathutils import Quaternion  # noqa: E402
from riggermortis_addon import pose_apply, scene_apply  # noqa: E402

OK = True


def check(label: str, ok: bool, detail: str = "") -> bool:
    global OK
    if not ok:
        OK = False
    print(f"RM_RUX {label}: {'PASS' if ok else 'FAIL'}"
          f"{(' ' + detail) if detail else ''}")
    return ok


def payload_file(name: str) -> str:
    """A REAL payload generated by verify_pose_apply.sh (read-only use)."""
    path = os.path.realpath(os.path.join(os.environ["RM_PAYLOADS"], name))
    if not os.path.isfile(path):
        raise RuntimeError(f"missing payload {path} (run the pose-verify "
                           "payload generation first)")
    return path


def fresh_scene() -> None:
    bpy.ops.wm.read_factory_settings(use_empty=True)


def enable_addon() -> None:
    import addon_utils

    addon_utils.enable("riggermortis_addon", default_set=True)


def first_armature():
    for obj in bpy.context.scene.objects:
        if obj.type == "ARMATURE":
            return obj
    raise RuntimeError("no armature found in scene")


def all_quats() -> dict:
    out = {}
    for obj in bpy.data.objects:
        if obj.type != "ARMATURE":
            continue
        for pb in obj.pose.bones:
            q = Quaternion(pb.rotation_axis_angle[1:4], pb.rotation_axis_angle[0])
            out[f"{obj.name}/{pb.name}"] = tuple(round(v, 9) for v in q)
    return out


def run_op(name: str, **kwargs) -> tuple[set, float]:
    mod, op = name.split(".", 1)
    t0 = time.perf_counter()
    result = getattr(getattr(bpy.ops, mod), op)(**kwargs)
    return result, time.perf_counter() - t0


def main() -> int:
    enable_addon()
    check("RUX-GATE-OPS", all(
        hasattr(bpy.ops.rm, n) for n in
        ("finger_fix", "face_trim", "figure_flip", "pin_retarget",
         "pin_confirm")),
        "the five fix operators registered")

    # -- the pose-level ops on the real metarig + its real payload ---------------
    bpy.ops.wm.open_mainfile(filepath=os.environ["RM_METARIG_BLEND"])
    enable_addon()
    obj = first_armature()
    settings = bpy.context.scene.rm_settings
    settings.payload_path = payload_file("metarig_payload.json")
    bpy.context.view_layer.objects.active = obj
    with open(settings.payload_path, encoding="utf-8") as fh:
        payload = json.load(fh)

    # the finger fix THROUGH THE OPERATOR (the interactive click-through)
    pose_apply.apply_payload(obj, json.loads(json.dumps(payload)))
    result, op_s_finger = run_op("rm.finger_fix", hand="hand.L", finger="ring",
                                 direction=(0.0, 0.0, -1.0))
    finger_ok = (
        result == {"FINISHED"}
        and "authored in review" in settings.last_report
    )
    # core-side numeric proof on the same payload: the authored chain is
    # straight along the drag at the canonical segment lengths, confidence
    # 1.0, ledger semantics clean (the metarig has no finger bones: the loud
    # capability note is the EXPECTED apply shape — never a silent no-op).
    pose_fixed = core.author_finger(
        core.CanonicalPose.from_dict(payload["pose"]),
        "hand.L", "ring", (0.0, 0.0, -1.0))
    chain = pose_fixed.hands["hand.L"].fingers["ring"]
    seg_err = max(
        abs(math.dist(chain.joints[a], chain.joints[b]) - want)
        for a, b, want in zip(("mcp", "pip", "dip"), ("pip", "dip", "tip"),
                              core.FINGER_SEGMENT_LENGTHS["ring"], strict=True)
    )
    finger_ok &= (
        seg_err <= 1e-9
        and chain.confidence == 1.0
        and any("authored in review" in n for n in pose_fixed.notes)
    )
    check("RUX-GATE-FINGER", finger_ok,
          f"op={result == {'FINISHED'}} seg_err={seg_err:.2e} u "
          f"op_s={op_s_finger:.4f}")

    result, op_s_face = run_op("rm.face_trim", param="smile.L", value=0.75)
    face_ok = result == {"FINISHED"} and "smile.L" in settings.last_report
    check("RUX-GATE-FACE", face_ok,
          f"op={result == {'FINISHED'}} op_s={op_s_face:.4f}")

    # -- the scene-level figure flip on the REAL multi-figure payload ------------
    fresh_scene()
    enable_addon()
    couple_gate.build_canonical_rig("RM_A", 0.0)
    couple_gate.build_canonical_rig("RM_B", -0.45)
    settings = bpy.context.scene.rm_settings
    settings.payload_path = payload_file("girls_multi.json")
    with open(settings.payload_path, encoding="utf-8") as fh:
        spayload = json.load(fh)
    labels = [str(e["label"]) for e in spayload["figures"]]
    flip_label = labels[1]
    settings.cast_slots.add().figure_label = labels[0]
    settings.cast_slots[0].armature = "RM_A"
    settings.cast_slots.add().figure_label = flip_label
    settings.cast_slots[1].armature = "RM_B"

    # DIRECT-path baseline: the flipped payload applied through the library
    flipped_ref = json.loads(json.dumps(spayload))
    scene_obj = core.scene_from_payload(flipped_ref)
    flipped_scene = core.flip_figure(scene_obj, flip_label)
    entries = {str(e.get("label")): e for e in flipped_ref["figures"]}
    for fig in flipped_scene.figures:
        entries[fig.label]["pose"] = fig.pose.to_dict()
    scene_apply.apply_scene_payload(
        flipped_ref, {labels[0]: "RM_A", flip_label: "RM_B"})
    quats_direct = all_quats()

    result, op_s_flip = run_op("rm.figure_flip", label=flip_label)
    quats_op = all_quats()
    figure_ok = (
        result == {"FINISHED"}
        and "flipped" in settings.last_report
        and quats_op == quats_direct  # the operator keys EXACTLY the direct path
    )
    check("RUX-GATE-FIGURE", figure_ok,
          f"op={result == {'FINISHED'}} quats_match_direct="
          f"{quats_op == quats_direct} ({len(quats_direct)} bones) "
          f"op_s={op_s_flip:.4f}")

    # -- the pin affordances through the LIBRARY path (in-memory fixture) --------
    # couple_gate's payload labels its two figures "A"/"B"
    pins = [{"figure_a": "A", "role_a": "hips",
             "figure_b": "B", "role_b": "hand.R",
             "origin": "suggested", "confidence": 0.4}]
    couple_payload = couple_gate._couple_payload(pins)
    scene_pin = core.scene_from_payload(couple_payload)
    retargeted = core.retarget_pin(scene_pin, 0, "a", "hand.L")
    confirmed = core.confirm_pin(retargeted, 0)
    couple_payload["pins"] = [p.to_dict() for p in confirmed.pins]
    report = scene_apply.apply_scene_payload(
        couple_payload, {"A": "RM_A", "B": "RM_B"},
    )
    pin_ok = (
        confirmed.pins[0].origin == "authored"
        and confirmed.pins[0].confidence == 1.0
        and "retargeted in review" in confirmed.pins[0].note
        and "confirmed in review" in confirmed.pins[0].note
        and report["figures_applied"] == 2
    )
    _op_s_pin = 0.0
    check("RUX-GATE-PIN", pin_ok,
          f"pin={confirmed.pins[0].figure_a}.{confirmed.pins[0].role_a} "
          f"authored={confirmed.pins[0].origin} "
          f"applied={report['figures_applied']}")

    # -- untouched path: a clean payload re-applies byte-identically -------------
    fresh_scene()
    bpy.ops.wm.open_mainfile(filepath=os.environ["RM_METARIG_BLEND"])
    enable_addon()
    obj = first_armature()
    settings = bpy.context.scene.rm_settings
    settings.payload_path = payload_file("metarig_payload.json")
    bpy.context.view_layer.objects.active = obj
    pose_apply.apply_payload(obj, json.loads(json.dumps(payload)))
    quats_a = all_quats()
    pose_apply.apply_payload(obj, json.loads(json.dumps(payload)))
    quats_b = all_quats()
    check("RUX-GATE-UNTOUCHED", quats_a == quats_b,
          f"clean re-apply byte-identical ({len(quats_a)} bones, 9 dp)")

    # -- refusals: bad props cancel loudly, nothing applied ----------------------
    # Background Blender raises an operator's ERROR report as RuntimeError to
    # the invoking script — that IS the loud CANCELLED path here.
    def refused(name: str, **kwargs) -> bool:
        try:
            return run_op(name, **kwargs)[0] == {"CANCELLED"}
        except RuntimeError:
            # Background Blender raises BOTH loud paths as RuntimeError: the
            # operator's ERROR report ("...refused: ...") and a failed poll
            # ("...poll() failed, context is incorrect"). Either = refused.
            return True

    refusals = 0
    bpy.context.view_layer.objects.active = obj
    for kwargs in (
        {"hand": "hand.C", "finger": "index", "direction": (1.0, 0.0, 0.0)},
        {"hand": "hand.L", "finger": "claw", "direction": (1.0, 0.0, 0.0)},
        {"hand": "hand.L", "finger": "index", "direction": (0.0, 0.0, 0.0)},
    ):
        if refused("rm.finger_fix", **kwargs):
            refusals += 1
    if refused("rm.face_trim", param="smile.C", value=0.5):
        refusals += 1
    if refused("rm.pin_retarget", index=0, endpoint="a", new_role="hand.L"):
        refusals += 1  # the metarig payload carries no pins -> loud refusal
    if refused("rm.figure_flip", label="no-such-figure"):
        refusals += 1  # pairings exist, label unknown -> core refuses
    check("RUX-GATE-REFUSE", refusals == 6,
          f"{refusals}/6 loud CANCELLED refusals (bad hand/finger/direction/"
          "param, pin-less payload, unknown figure)")

    # -- determinism: the finger fix runs twice, applied quats identical ---------
    fresh_scene()
    bpy.ops.wm.open_mainfile(filepath=os.environ["RM_METARIG_BLEND"])
    enable_addon()
    obj = first_armature()
    settings = bpy.context.scene.rm_settings
    settings.payload_path = payload_file("metarig_payload.json")
    bpy.context.view_layer.objects.active = obj

    def run_twice() -> tuple[dict, dict]:
        pose_apply.apply_payload(obj, json.loads(json.dumps(payload)))
        run_op("rm.finger_fix", hand="hand.L", finger="ring",
               direction=(0.0, 0.0, -1.0))
        q1 = all_quats()
        pose_apply.clear_pose(obj)
        pose_apply.apply_payload(obj, json.loads(json.dumps(payload)))
        run_op("rm.finger_fix", hand="hand.L", finger="ring",
               direction=(0.0, 0.0, -1.0))
        q2 = all_quats()
        return q1, q2

    q1, q2 = run_twice()
    check("RUX-GATE-DETERM", q1 == q2,
          f"twin click-throughs byte-identical ({len(q1)} bones)")

    total_op_s = op_s_finger + op_s_face + op_s_flip + _op_s_pin
    check("RUX-GATE-T2F", total_op_s < 15.0,
          f"Blender op wall-clock: finger={op_s_finger:.4f}s face="
          f"{op_s_face:.4f}s figure={op_s_flip:.4f}s — the op component of "
          "the probe's declared interaction model "
          "(CLICK 1.0 / DRAG 3.0 / SLIDER 2.0 + op)")

    print("RM_RUX GATE:", "PASS" if OK else "FAIL")
    return 0 if OK else 1


if __name__ == "__main__":
    raise SystemExit(main())
